apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
        - name: welcome
          image: localtesting/welcome
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: welcome-config
            - secretRef:
                name: welcome-secret
